### ISSUE TITLE
Incompatibility with Canals (formerly: Potential crash with Hydrogen/Phosphor reforged)

### ISSUE THREAD

**Issue by Drakoflame** [MaxNeedsSnacks/roadrunner#11]
I highly suspect that HydrogenReforged and PhosphorReforged are the cause of this crash, as I'm writing this up I have both of them disabled to test if that is the issue or not, I'll include crash/logs as soon as they're done compiling. Until then here is the crash _WITH_ those two mods installed (note, Optifine is installed, still unsure of incompatibility or not, I'll atempt again later if you would like)

https://pastebin.com/yLnJrEcN

**Comment by Drakoflame** [comment]
Just as I hit "comment" the game loaded- then crashed. 

https://pastebin.com/3Ss9cpKb


Edit: Going to attempt again (with Hydrogen/Phosphor) without Optfine, to see if I get different results. Reminds me of a saying... "The definition of insanity, is repeating the same thing over and over, and expecting different results", or something like that XD

**Comment by Drakoflame** [comment]
Alright, I'm back. I disabled OpenLoader instead of Optiforge, so I had to completely retest... I feel like a dunce XD

ANYWAY! Here are the crash reports
With H/P:
https://pastebin.com/v7wbydt8
W/o H/P:
https://pastebin.com/qC36mZTZ

I'm not sure what else might be causing the issue, I don't THINK I have anything else that's incompatible performance wise. The only mods that I can really think of that could be causing issues are Flywheel and Ferritecore. I'll give it a shot w/o those enabled (might take me a bit longer, gotta disable dependents for Flywheel and I forget which they are)

**Comment by MaxNeedsSnacks** [comment]
Some mod seems to be firing FMLCommonSetupEvent multiple times, so this issue seems to go **well** beyond RoadRunner. Check all of the other errors of mods complaining about things already being registered :p

**Comment by Drakoflame** [comment]
I'm not sure which ones those might be. I did disable the mods I thought would be causing the issue (still crashed https://pastebin.com/U1VLGtrx )

I did scroll down a bit and was looking at the error and saw which mods are being suppressed. While I know it's lazy to say this, but as much as I would love to figure out what the hell is causing this, I also do want to play minecraft, and was able to get the game playable using Hydrogen/Phosphor. It's really strange because a week ago, I was having no issues at all, and was even able to run the game with Shaders at a playable frame rate (if you call 40~ playable). I wish I could remember what mods I updated/what versions, so I could go through the process of rolling back until I get my framerate back again, but as it stands it takes anywhere from 5-10 minutes for the game to boot up. 

I'm almost wondering if my issues are a combination of incompatibilities **AND** hardware issues. I know my Hard Drive is on the slow end for things, and my CPU, while once good, is now on the low end, as well as my graphics card. Upgrading to something better would be nice, but that requires money, something I'm lacking greatly.

I'll keep trying things for a bit longer to try and find the solution for this, but I'll let you decide if the issue should be closed for now or not. I'll keep posting logs on this issue to avoid creating more additional (possibly duplicate) errors. I'll also try to do it in bulk loads so you don't get spammed with my comments XD

**Comment by Drakoflame** [comment]
Still dissabling mods for testing, but I noticed RoadRunner _ITSELF_ showed up in the "Suppressed" list...

**Comment by Drakoflame** [comment]
Alright. Didn't take as long as I was expecting! I've disabled ALL the mods (expect for Forge and Roadrunner, _obviously_) that showed up in the "suppressed/already initialized" part of the previous log(s). and I'm still getting, effectively, the same crash. Now, I'm pretty sure it doesn't need to be said, but I _don't_ get this crash when Roadrunner isn't installed, so I'm not sure what's happening, and if it's already an issue but isn't crashing, something Roadrunner is doing is exacerbating the issue and making it crash. Perhaps it's a Forge version issue? Maybe it really is just my crappy PC hiccuping causing everything to load twice, or whatever. Hopefull you, or someone else having this issue, is able to figure something out and put and end to this issue once and for all.

Thanks for dealing with me and my cursed problem, I'll attach the crash report, latest.log, and debug.log, so hopefully we can figure this issue out!

Crash: https://pastebin.com/kWUEdYT5
Latest: https://pastebin.com/50WeQ2Cy
Debug: https://pastebin.pl/view/ad4203d1 (again, different site due to it being to large for the other pastebin)

**Comment by Drakoflame** [comment]
Okay for shits and giggles I did the old tried and trued method of disabling EVERY other mod and clicked "Play"


Guess what... It loaded JUST FINE... so that means there's something **ELSE** causing issues here... I'm going to start with API mods (as those dig into forge/minecraft to make changes)

**Comment by Drakoflame** [comment]
HOLY FUCK I FOUND IT!!!


It only took me three hours (I had to stop at 2pm, 2 hours after the last comment for an appointment and didn't get back until like 45 minutes ago or so), BUT I FINALLY FUCKING FOUND IT.

This would have only been a half hour search if I'd started at the **TOP** of the list and worked from A to Z.. but _nnnooOOOOooo_, my dumb ass had to start at the bottom and work my way UP... 
https://www.curseforge.com/minecraft/mc-mods/canals/ is the culprit. I'm going to drop this crash in their laps as well so that they can try to figure out the issue. It is a WIP mod so bugs are to be expected, a few of them they're even aware of are _visual_ issues, so it'd make sense that a mod like this that effects _visual_ things would cause issues. 

I'm just so glad I found the issue... sure I had to brute force it... but the GDLauncher lets me just 'dissable' a mod, without having to actually remove it from my mods folder, like YEE OLDEN DAYS of modding XD. I'm going to end with the crash report.

Thank you for putting up with me x wx

https://pastebin.com/Hbc7gs5m

**Comment by MaxNeedsSnacks** [comment]
Neat! Just out of interest, are you absolutely sure it's Canals though? That mod seems to only add one very simple block, and nothing in the source exactly jumps out at me as being particularly problematic...?

**Comment by Drakoflame** [comment]
Absolutely 110% positive 
![image](https://user-images.githubusercontent.com/8823913/136139128-92ed9a2a-504c-4012-97c4-9f62f14da8fa.png)

Canals is not installed and game booted up

**Comment by Mr-Syntax** [comment]
canals is incompatible with my pack so it might be an issue on their side

**Comment by Drakoflame** [comment]
I'm going to close the issue now, the V1 of the Canals mod _IS_ incompatable with Roadrunner, but the V2 seems to be working fine (haven't had a crash on startup, doens't mean it might not crash still).

Anyone having this issue and are using the 1.0 version of the Canals mod. Update to the newer version, it _seems_ to have fixed the issue
