### ISSUE TITLE
Mixin Crash 

### ISSUE THREAD

**Issue by WenXin20** [MaxNeedsSnacks/roadrunner#14]
`Minecraft v1.16.5`
`Forge v36.2.4`
`Roadrunner v1.3.0`

### Reproduction Steps
- The game crashes on startup, likely a mixin conflict with another mod, possibly with Forgery.

### Crash Report File
- [Crash Log](https://gist.github.com/WenXin20/d0283f7f1408620c3b05406723f94750)

**Comment by MaxNeedsSnacks** [comment]
Hm... ATs seem to be applied before Overwrites, so if **any** mod ATs a method we overwrite while retaining its original visibility (likely private), we'll crash.
Might wanna go over our Overwrites and fix them :/
