### ISSUE TITLE
Tried switching performant for roadrunner crashed after the first few chunks

### ISSUE THREAD

**Issue by Mr-Syntax** [MaxNeedsSnacks/roadrunner#15]
my pack has 280+ mods and i was trying with optifine G7 aswell so i know its a tall order, i just wanted to see if there was something to gain since my load times are pretty long and ram usage is pretty high

https://www.curseforge.com/minecraft/modpacks/chosencraft
[crash-2021-10-15_07.52.38-server.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/7351210/crash-2021-10-15_07.52.38-server.txt)

**Comment by Mr-Syntax** [comment]
thanks for trying to fix this guys

would be pretty stoked if it could make the pack run even more smoothly im pushing an update later today which will take it above 300 mods still vanilla ++

really hope you can figure it out

btw, do you know of the mod called FarPlane2

it essentially makes LOD for minecraft, i think this might be the single biggest optimization that could be made on the game
https://github.com/PorkStudios/FarPlaneTwo

if you could make some texutre decimator system where for example a 16x texture gets converted to a 8x texture if it is more than 4 chunks (sphere radius) away all the way to 1 pixel i think this could really revolutionize the game

furthermore in my pack actually there is alot of estethic decorations like bushes and such, if you could make them only render at a max 4 chunk distance that could also boost performance quite a bit, now im not a coder so i ofc dunno if this is even possible but its just something that i have been thinking about when ive been flying around the world 

another thing i have thought about is that, does the block properties also get loaded when they are that faraway? like if they are destroyable or not and stuff like that? that could also be brought down to a small radius around the player

**Comment by ghost** [comment]
I'd like to add something:

Tried to run BOTH Performant and Roadrunner - game crashes, they are not compatible.
It would've been cool if this actually worked, "wow, double the performance!" - _I thought._
maybe they just do too much of the same? - I am a newby in this, so yeh.

[Ps. Optifine works pretty good with either Performant or Roadrunner]

**Comment by Mr-Syntax** [comment]
i know my guy, but yeah performant and road runner optimize in the same areas so they are not compatible

**Comment by Necxx** [comment]
Putting this in rules.properties in the config gets mc working.

mixin.ai.nearby_entity_tracking.goals=false

mixin.gen.features=false

mixin.ai.poi.fast_retrieval=false

Haven't tested with other mods and its a pretty hacky way to get the two mods to work so don't expect much.
Hope it helped.

**Comment by MaxNeedsSnacks** [comment]
I'm going to be assuming that mostly the `gen.features` rules are somehow incompatible with Terraforged here, but unfortunately, I don't have enough time to investigate this thoroughly myself, so I'll have to close this issue for now, sorry about that :/
