### ISSUE TITLE
[v1.3.0] Mixin Issue - Add compat with WYML?

### ISSUE THREAD

**Issue by Cixon** [MaxNeedsSnacks/roadrunner#17]
**Description:** The mixin mixin.alloc.chunk_ticking doesn't like WYML and the only way around it is disabling it. Perhaps there's a possibly to add a way around it for it to function differently if it detects WYML installed?

**Mod in question:**
https://www.curseforge.com/minecraft/mc-mods/wyml/

**Comment by Cixon** [comment]
Tested on a server environment.
**Forge Version:** 36.2.6

**Comment by MaxNeedsSnacks** [comment]
I've talked to the maintainers of WYML, and this should be a *fairly* simple fix on their end hopefully, we'll know more once they get back to me

**Comment by Cixon** [comment]
sweet looking forward to it!

**Comment by MaxNeedsSnacks** [comment]
Fixed on WYML's end \o/
