### ISSUE TITLE
Crash with ragnamod 6 latest version

### ISSUE THREAD

**Issue by Tealwen** [MaxNeedsSnacks/roadrunner#19]
### Reproduction Steps
install on mod server launch next crash

whe i don't have the mod installed it doesn't crash

### Crash Report File
[https://mclo.gs/sm5RQvs](https://mclo.gs/sm5RQvs)

**Comment by MaxNeedsSnacks** [comment]
Ragnamod uses an outdated version of BYG (Oh The Biomes You'll Go), you'll need to update to version 1.3.5 to fix this
