### ISSUE TITLE
a lot of issues and bugs #1

### ISSUE THREAD

**Issue by AbdElAziz333** [MaxNeedsSnacks/roadrunner#2]
Hi, i have downloaded the mod and worked perfect with some other performance mods but while testing it on some modpacks it showed some bugs.

1- When using RoadRunner with Performant it will cause crash report.
2- When using RoadRunner with Oh The Biomes you will go while creating new world it will freeze world generation like this:
https://i.imgur.com/ONsrg4Q.png
And the game can only be closed with the Task Manager (End Task)
3- when i added Roadrunner into this pack https://www.curseforge.com/minecraft/modpacks/world-of-beasts
after removing biomes you will go and halogen it opened like this:
https://i.imgur.com/WjruE53.png
but when i have downloaded some of the mods in other instance it opened perfect:
https://i.imgur.com/wa2JkDL.png

If there's anything else i can do for you please don't hesitate to ask.

**Comment by MaxNeedsSnacks** [comment]
Alright, so...
1) This is expected. RoadRunner isn't compatible with Performant, and as we both target *pretty* similar performance vectors, it is unlikely that they will ever be.
2) This may be related to a known crash with BYG, we're working with Corgi on a quick fix.
3) I honestly don't know much about this pack unfortunately, so I'd need some more info on what mod specifically could be causing this with RoadRunner (if any)

**Comment by MaxNeedsSnacks** [comment]
Can you get me a log file for the second crash by any chance? Suspecting it's the same as #4

**Comment by NathanDreamweaver** [comment]
Not the OP, but here is my crash log with only RoadRunner and Oh The Biomes You'll Go upon attempting to create a world (however, the game crashes by itself, no need to kill it) https://paste.ee/p/w1tRM

**Comment by MaxNeedsSnacks** [comment]
That's a different crash, see #7

**Comment by NathanDreamweaver** [comment]
Ah, here is the proper one with RoadRunner 1.1.1 then https://paste.ee/p/cFyAx
![image](https://user-images.githubusercontent.com/15868262/135914830-92dc1365-5e80-4905-9393-4c8822520922.png)

**Comment by MaxNeedsSnacks** [comment]
Talked about this issue with Corgi, he's already fixed this for Fabric 1.17 by using a different injection point and will backport the same fix to 1.16 soon(tm)

**Comment by EJK3903** [comment]
im trying to run the this with the modpack called better minecraft plus. here is the pastebin of crash https://pastebin.com/AUHG4YVy

**Comment by MaxNeedsSnacks** [comment]
Better Minecraft Plus uses Performant, which is not and will likely never be compatible with RoadRunner

**Comment by AbdElAziz333** [comment]
Every bug listed here with byg and with this pack are fixed in the newer versions of roadrunner
Thank you so much!
