### ISSUE TITLE
[RE] Updated BYG and always crashin

### ISSUE THREAD

**Issue by Tealwen** [MaxNeedsSnacks/roadrunner#20]
### Reproduction Steps
- launch server
- crash on loading map

not crash when not installed

### Crash Report File
[https://mclo.gs/4PSJqP1](https://mclo.gs/4PSJqP1)

### Additional Information
I have update byg to 1.3.5 and it's crash on startup

**Comment by MaxNeedsSnacks** [comment]
You're using Mohist / arclight, which is an implementation of Bukkit on top of Forge. Unfortunately, because of the way Bukkit overwrites Vanilla code in a lot of places, we can't guarantee compatibility with it. Can you try reproducing this without Bukkit?

**Comment by Tealwen** [comment]
if i use an new generated map it works with Mohist and Loliserv but if i use my map of my server it crash well sry for disturbing ^^
