### ISSUE TITLE
Crash when leaving a world

### ISSUE THREAD

**Issue by FishyBusinessYT** [MaxNeedsSnacks/roadrunner#22]
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

1- Open a minecraft world.
2- Leave, then lower the laptop screen while it's closing.
3- Open up the laptop, unlock it (after a while).
4- See that the game just crashed.

Extra: Mc was "not responding" when I lowered the screen, but I couldn't react fast enough to let it think.

Please mention why you think Meep Meep! may be the cause of the crash. If possible, please confirm that the crash does not happen when Meep Meep! is not installed: The crash log was mentioning screen render issues, so I'm fairly sure the issue is on RR's side, if not, I'm happy to report this where it corresponds.

### Crash Report File
https://gist.github.com/FishyBusinessYT/488b731b2cc6cce81ee011a8cd29567b#file-crash-2021-10-28_12-12-45-client-txt

### Additional Information

RR version: 1.3.0
Forge version: 36.2.8
No idea where to find the other logs

Please contact me if there's absolutely anything else that you need, since I could not provide much information about the issue.
I can also upload the world if necessary

**Comment by MaxNeedsSnacks** [comment]
The stacktrace seems to mention two other mods specifically, _Magnesium_ and _Seamless Loading Screen_, so I think this issue might be on them. RoadRunner doesn't really do much wrt client-side optimisations, and the actual issue seems to be with the world's session.lock file if I had to guess (which we don't mess with iirc), so I don't think this is related to RR, sorry :/
