### ISSUE TITLE
Incompatibility with ZYCraft

### ISSUE THREAD

**Issue by MojangPlsFix** [MaxNeedsSnacks/roadrunner#24]
### Expected Behavior
When generating ZYCraft Clusters the WorldDecoratingHelper should return a valid BlockState for generation

### Actual Behavior
Sometimes A Nullpointer Exception is thrown, that the chunk does not exists.

### Reproduction Steps
This can randomly happen.

### Attachments
nikita488/ZYCraft#17
[crash-2021-10-29_23.07.11-server.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/7446122/crash-2021-10-29_23.07.11-server.txt)
Playing on ATM 6 1.8.8

**Comment by embeddedt** [comment]
If this can still be reproduced on RoadRunner 1.5.0 with up-to-date mods, please open a new issue. The problematic mixin was analyzed, and I don't see a logic difference from vanilla. (In other words, I would expect vanilla to also throw its equivalent error in this situation.)
