### ISSUE TITLE
Log Spam with modded structure generation causing possible client side lag

### ISSUE THREAD

**Issue by NighthowlerStudios** [MaxNeedsSnacks/roadrunner#25]
### Actual Behavior
When a mod such as When Dungeons Arise, Repurposed Structures, or any of Yung's mods are installed, it seems there is log spam every new chunk about the mod struggling to handle generation of structures. this can result in a log spam so intense the client will have framerate jitter.

### Attachments
The below is just a few lines of over ten thousand that occured in as little as two minutes.  all of them are similar, but the result is the name of completely different structure blocks each until another second has passed, where it shows even more of them.  Have you made the structure registry in a way that isn't what mods expect?

"[19:32:50] [Server thread/ERROR]: Unknown structure start: zombie dungeon
[19:32:50] [Server thread/ERROR]: Unknown structure start: repurposed_structures:mineshaft_stone
[19:32:50] [Server thread/ERROR]: Unknown structure start: skeleton dungeon
[19:32:50] [Server thread/ERROR]: Unknown structure start: dungeons_arise:monastery
[19:32:50] [Server thread/ERROR]: Unknown structure start: dungeons_arise:heavenly_challenger
[19:32:50] [Server thread/ERROR]: Unknown structure start: repurposed_structures:village_mountains
[19:32:50] [Server thread/ERROR]: Unknown structure start: small dungeon"

**Comment by Kaleidio** [comment]
https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/53#issuecomment-955581083

See Sodium Forge fork Magnesium issue above, might be related or the cause.

**Comment by MaxNeedsSnacks** [comment]
We don't really do much by way of structures, really, apart from one contribution TG has made to upstream Lithium (`mixin.gen.features`) and one fast access mixin by Jelly that's meant to circumvent nested stream code (`mixin.world.mob_spawning`).

Can you try to disable either of those two rules and see whether the log spam persists? It's possible that this is either related to some Forge patch we didn't account for, or that this issue is actually unrelated to RR altogether.

**Comment by Kaleidio** [comment]
which file do I use to disable them and what is the syntax?  I had done it in the past but I have forgotten how

**Comment by NighthowlerStudios** [comment]
sure, one min

**Comment by NighthowlerStudios** [comment]
disabling mixin.gen.features worked.  something must be borked in there

the structure mods I use definitely have mixins injecting into that class as well. it might actually be a mixin collision that isn't crashing but just resulting in unexpected behaviour

**Comment by NighthowlerStudios** [comment]
seemed to have been a mod conflict with some specific mod as even with mixin.gen.features missing the issue is no longer present. considering this issue closed.
