### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by InteJason** [MaxNeedsSnacks/roadrunner#27]
RoadRunner-mc1.16.5-1.3.0.jar
Forge 36.2.8

Crashes only with roadrunner installed: https://paste.ee/p/3d3YZ

**Comment by MaxNeedsSnacks** [comment]
This seems to be a duplicate of #5, remove Simply Improved Terrain or disable the conflicting rule as outlined here: https://github.com/MaxNeedsSnacks/roadrunner/issues/5#issuecomment-932954008 ^^
