### ISSUE TITLE
Crash when using ByG

### ISSUE THREAD

**Issue by Krampus69** [MaxNeedsSnacks/roadrunner#28]
Hello 👋 
I'm having some crashes when using Roadrunner and loading chunks.

1. Use ByG
2.  Load chunks
3. Crash

Here is the crash report :) I'm not a pro so I can't tell whether it's Roadrunner's fault or not but its name is in this crash report so...

[crash-2021-11-01_22.30.47-server.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/7456342/crash-2021-11-01_22.30.47-server.txt)

I'm on Minecraft 1.16.5 - Forge 36.2.4 and I'm using RoadRunner-mc1.16.5-1.3.0

**Comment by ModernGamingWorld** [comment]
@Krampus69 What version of BYG are u using cause they fixed issues with road runner in this https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3485079

**Comment by MaxNeedsSnacks** [comment]
This... seems to be the same as #26 crashwise, @TYPyz have you managed to find the culprit of your issue by any chance?

**Comment by Krampus69** [comment]
Hello,
I'm using the latest ByG version on 1.16.5 (Biomes You Go 1.3.5 MCV: 1.16.5)

But to be honest I think it has nothing to do with Roadrunner. I've been doing some testings and crashes still occur even without Roadrunner on new worlds. 
Here is a crash log without Roadrunner installed :
[crash-2021-11-01_23.57.54-server.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/7462459/crash-2021-11-01_23.57.54-server.txt)

So yeah, the crash could be because of ByG and not Roadrunner, I'm guessing we could read "Lithium" and "Roadrunner" in the first crash log only because it is how the game is handling some aspects of the engine, and without Roadrunner it is still happening so...
I've made a post on ByG github too, hopefully they'll help me find out where is this issue from
