### ISSUE TITLE
Incompatibility with Simply Improved Terrain [Forge]

### ISSUE THREAD

**Issue by SkullDiamond** [MaxNeedsSnacks/roadrunner#29]
I test it whit only with roadrunner and Simply Improved Terrain [Forge]. You cant even launch the game 

![image](https://user-images.githubusercontent.com/79324102/139778793-9688dcf0-d51f-42b1-ae6f-45209618fffc.png)

**Comment by MaxNeedsSnacks** [comment]
Duplicate of #5 and #27, please check for existing issues before opening a new one
