### ISSUE TITLE
Crashing while in the nether

### ISSUE THREAD

**Issue by FeikoJoosten** [MaxNeedsSnacks/roadrunner#31]
### Reproduction Steps
It's high likely that I'm reporting this to the wrong mod-dev, but I'm guessing it's coming from the Roadrunner mod. 
I'm getting reports from players on the server that whenever they are in the Nether, the server crashes over and over again.

### Crash Report File
[crash-2021-11-06_14.43.53-server.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/7490695/crash-2021-11-06_14.43.53-server.txt)

**Comment by malte0811** [comment]
This seems to be a ForestCraft issue, I found a crashlog for the same crash without RoadRunner in their CF comments section: https://pastebin.com/VzUaGR2f

**Comment by FeikoJoosten** [comment]
Awesome, thank you, onto ForestCraft it is!
