### ISSUE TITLE
Crash with Sodium-Forge (Halogen) 2.9.10

### ISSUE THREAD

**Issue by SweptWasTaken** [MaxNeedsSnacks/roadrunner#32]
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

1. Load a fresh instance of Minecraft 1.6.5
2. Install latest Forge version
3. Add [sodium-forge](https://www.curseforge.com/minecraft/mc-mods/halogen/download/3410021) and [Roadrunner](https://www.curseforge.com/minecraft/mc-mods/roadrunner/download/3487988).
4. Crash.

Removing Roadrunner stops the game crashing.

Please mention why you think Meep Meep! may be the cause of the crash. If possible, please confirm that the crash does not happen when Meep Meep! is not installed.

### Crash Report File
https://paste.ee/p/057ef

### Additional Information
Provide any additional information or context which may be relevant to the issue. If you have none to add, you can remove this section.

**Comment by MaxNeedsSnacks** [comment]
See #2, RoadRunner and Halogen aren't compatible with one another (I'm... pretty sure I marked them as incompatible on CurseForge as well? If I didn't I'll fix that real quick sorry about that)
