### ISSUE TITLE
Issue with Revamped Wolf and Roadrunner

### ISSUE THREAD

**Issue by SHXRKIEgg** [MaxNeedsSnacks/roadrunner#37]
### Expected Behavior
Wolf shouldn't move when sitting

### Actual Behavior
Wolf moves while sitting

### Reproduction Steps
Add Revamped Wolf and Roadrunner and tame a wolf and drop steak on the ground and the Wolf moves while sitting

**Comment by embeddedt** [comment]
Thanks for the report, will be fixed in 1.5.1. (Please ignore the fact that it has been two years.)
