### ISSUE TITLE
[1.16.5] [1.1.1] Incompatible mod mixins. Needs support.

### ISSUE THREAD

**Issue by Cixon** [MaxNeedsSnacks/roadrunner#4]
**Forge Version:** v36.2.6
**RoadRunner Version:** v1.1.1

### Mod Mixins mentioned in crash report (line 92);
-[Architectury](https://www.curseforge.com/minecraft/mc-mods/architectury-forge) - (for ftbchunks,ftblibrary,ftbranks, and ftbteams.)
-[BetterEnd (forge)](https://www.curseforge.com/minecraft/mc-mods/betterend-forge-port)
-[RandomPatches](https://www.curseforge.com/minecraft/mc-mods/randompatches-forge)
-[Origins (forge)](https://www.curseforge.com/minecraft/mc-mods/origins-forge)
-[Pehkui (forge)](https://www.curseforge.com/minecraft/mc-mods/pehkui/files/3457597) - (for the mod [simplyorigins](https://www.curseforge.com/minecraft/mc-mods/simplyorigin-forge-fabric/files/3469178).)
-[Structure Gel API](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)

### Crash Report File
[crash-2021-10-02_20.30.35-fml.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/7272204/crash-2021-10-02_20.30.35-fml.txt)
### Latest Log File
[latest.log](https://github.com/MaxNeedsSnacks/roadrunner/files/7272205/latest.log)

**Comment by MaxNeedsSnacks** [comment]
This seems to be caused by an access transformer making a method public that RoadRunner then attempts to overwrite with a private method. I'll just make the overwrite public for now, so this shouldn't be an issue in the future
