### ISSUE TITLE
Server started up with RoadRunner installed, but my 2 others will not

### ISSUE THREAD

**Issue by antibang** [MaxNeedsSnacks/roadrunner#41]
### Expected Behavior
All 3 servers using my modpack would start up with RoadRunner installed, however only one will fully boot up with the mod installed.

### Actual Behavior
So, I have 3 servers running my modpack, so they all have the same mods and whatnot installed (but if imma be honest, I can't guarantee that all the mods are updated to the exact same versions, though I'm usually good about keeping everything the same. I recently have updated a few mods that fixed incompatibilities with RoadRunner as well). My third server finally started up with RoadRunner installed, so I thought I could finally add it to my other two, but the same issue still persisted. They would get stuck on the very last part of booting up.

I feel bad because I think this is a duplicate issue, but I wasn't able to find it again :( no crashing or anything tho. I will include a log from one of the servers that won't start up and one log from the server it will start up on! Also, there probably are some small differences between all the servers (like config differences) because it's really hard keeping up with all 3 that serve different purposes, but they should all have the same mods. If you need any other information, just lemme know

### Attachments
Log from the server that DOES NOT start up with RoadRunner:

[latest_extended.log](https://github.com/MaxNeedsSnacks/roadrunner/files/7664796/latest_extended.log)

Log from the server that DOES start up with RoadRunner:

[latest_event.log](https://github.com/MaxNeedsSnacks/roadrunner/files/7664797/latest_event.log)

**Comment by antibang** [comment]
I don't know if it's worth mentioning, but I was experimenting with other performance mods on both client and server side. I tested the mod Starlight. **_The exact same thing happened._** Like, identical issue.

Dunno if this helps or not. It's not crashing during start up either. It just freezes, or becomes stuck. Just wanted to clairify.

**Comment by MaxNeedsSnacks** [comment]
Hm... if this happens with other, unrelated performance mods as well, I doubt this is a RoadRunner issue, sorry :/

It might be worth checking this out with whoever is hosting these (also maybe worth looking into the differences in configuration, like the Java version *and vendor* on each one of them) instead
