### ISSUE TITLE
Low Hanging fruit

### ISSUE THREAD

**Issue by Mr-Syntax** [MaxNeedsSnacks/roadrunner#44]
***disclaimer i dont know how to code***

okay guys i have bothered you before regarding 1 sec full world stops i was having in my pack
https://www.curseforge.com/minecraft/modpacks/chosencraft

i finally found a semi fix, it doesent do it as often as before and the spike are way shorter this was the fix

after searching abit on how to fix garbage collection stutters i found a thread where some told me to try these custom JVM arguments
-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1

it definently helped, so if you could somehow incorporate this into the mod i think it would be great, cause you cant ship a pack with custom JVM arguments as far as i know 

i cant get roadrunner to work atm in my pack because of a crash with astikorcarts but i will post that in a seperate thread

**Comment by MaxNeedsSnacks** [comment]
We will not be adding default launch arguments to Minecraft, that is completely out of the scope of (almost) any mod, sorry
