### ISSUE TITLE
Crash with astikor Carts

### ISSUE THREAD

**Issue by Mr-Syntax** [MaxNeedsSnacks/roadrunner#45]
[crash-2021-12-21_00.47.17-fml.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/7748591/crash-2021-12-21_00.47.17-fml.txt)

i tried switching performant for road runner in this pack, and now astikorcarts crashes during startup phase

https://www.curseforge.com/minecraft/modpacks/chosencraft

**Comment by malte0811** [comment]
Can you upload the full debug.log? This looks like something might be going wrong earlier without crashing properly.

**Comment by Mr-Syntax** [comment]
where do i find that brother?

**Comment by MaxNeedsSnacks** [comment]
It should be in the `logs` folder of your instance

**Comment by MaxNeedsSnacks** [comment]
Gonna be closing this issue for now since we don't have enough information to go by here, unfortunately. Feel free to reopen if this still occurs in the future ^^
