### ISSUE TITLE
LOD system

### ISSUE THREAD

**Issue by Mr-Syntax** [MaxNeedsSnacks/roadrunner#46]
Okay so i know there is this mod Farplane2 
https://github.com/PorkStudios/FarPlaneTwo/

and what it does is allow you to have massive render distances which is to me the holy gradle of optimization
like if you can run the best looking resource pack with shaders but only at 2 chunk render distance its meaningless...

so i was thinking a good place to start could be a max render distance for Sprites (i mean grass shrooms etc) 
so you could set a slider in the menu for how far away they can render at max
so if you set it to 6 chunks for example sprites will only render in that distance
all blocks would still be rendered normally

all tho making some kind of converter that can automatically decimate textures to lower res would be ideal for all blocks
so that it automatically scales down the res when they are so far away you can see the difference anyway, kinda like nanite does for Unreal 5

i know this is a big one but i honestly think its the most heavy hitting optimization you could make.
just the sprites for a start would make a huge difference
please do tell me if this makes no sense i will try to explain it better

**Comment by MaxNeedsSnacks** [comment]
An LOD system is way too far outside the original spec for a mod based on Lithium (with **correctness** and Vanilla-adjacency being some of its major selling points), and I see no good way or reason to implement it in 1.16 when the current 1.12 iteration isn't even fully up and running, sorry :/
