### ISSUE TITLE
Crash with immersive geology

### ISSUE THREAD

**Issue by Cynix32** [MaxNeedsSnacks/roadrunner#49]
### Reproduction Steps

Just use these mods:
RoadRunner-mc1.16.5-1.4.0.jar
ImmersiveEngineering-1.16.5-5.0.7-143.jar (this is a dependency of immersive geology)
immersive_geology-1.0v5.jar
Then launch minecraft forge

### Crash Report File
pastebin.com/QEvD4BJN

### Additional Information
Forge 36.2.22
MC 1.16.5
Java 8

**Comment by malte0811** [comment]
The same crash also happens without RR when placing Immersive Geology uranium sheetmetal stairs, see https://github.com/Immersive-Geology-Team/Immersive-Geology/issues/91.

For future reference, when you report a bug to multiple mods it's useful to add links to the other reports.
