### ISSUE TITLE
Server Crashes on Startup

### ISSUE THREAD

**Issue by TheRealDadbeard** [MaxNeedsSnacks/roadrunner#50]
Using Valhelsia 3 Modpack and have attached the log what happens. I have no idea which mods causes it.

Minecraft 1.16.5
Valhelsia 3 3.4.8
Forge 1.16.5-36.2.22

[debug.log](https://github.com/MaxNeedsSnacks/roadrunner/files/7800249/debug.log)
[latest.log](https://github.com/MaxNeedsSnacks/roadrunner/files/7800250/latest.log)

**Comment by MaxNeedsSnacks** [comment]
Valhelsia 3 uses Performant, which is not and will never be compatible with RoadRunner, see #10 (https://github.com/MaxNeedsSnacks/roadrunner/issues/2#issuecomment-934590788)
