### ISSUE TITLE
Crash with immersive engineering

### ISSUE THREAD

**Issue by TheRealDadbeard** [MaxNeedsSnacks/roadrunner#51]
Minecraft 1.16.5
Valhelsia 3 3.4.8
Forge 1.16.5-36.2.22

[crash-2022-01-02_16.28.02-client.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/7800257/crash-2022-01-02_16.28.02-client.txt)

**Comment by MaxNeedsSnacks** [comment]
Can you please try to reproduce this without OptiFine enabled? OF is known to cause issues with both RoadRunner and just other mods in general

**Comment by TheRealDadbeard** [comment]
It was performant in the pack. I did not know it was inlcuded. I removed it and added roadrunner as per your other comment on one of my issues. Now my client and the server start with it.
