### ISSUE TITLE
Client hangs on "Waiting for server" due to LithiumServerTickScheduler.getPending()

### ISSUE THREAD

**Issue by QuestingPet** [MaxNeedsSnacks/roadrunner#52]
### Expected Behavior
The client should not hang on "Waiting for server". I tested that this does not occur when Meep Meep! is not installed.

### Actual Behavior
After a few minutes, the client hangs on "Waiting for server" and the world is not playable.

I am playing a singleplayer FTB OceanBlock 1.11.0 world (1.16.5). The client seems to hang while waiting for the singleplayer server during chunk saves (I think). This can cause the game to essentially be unplayable for >10min for the tick to process. Subsequent ticks also hang for a bit.

On this world, I have a few dozen Hydroponic Beds being tick accelerated every tick using Integrated Dynamic's Player Simulator with Acceleration Wands. Everything is fine for a while until this several minute tick tries to process (see below). Quitting and continuing has the same, where I can play just fine for a few minutes until all of a sudden the server can't keep up as it's processing this very long tick.

### Attachments
Here's a spark profiler I did on the singleplayer server which shows a >10min tick time waiting for `LithiumServerTickScheduler.getPending()`. https://spark.lucko.me/5BliGelfVU

As mentioned above, in case it matters, I have a few dozen Industrial Foregoing's Hydroponic Beds being ticket accelerated every tick with Integrated Dynamic's Player Simulator and Acceleration Wands (one hydroponic bed = one player simulator and acceleration wand). Again, most ticks behave just fine, except for the occasional ones like in the profiler, rendering the session unplayable. 

As a temporary workaround, I've disabled roadrunner for this modpack, and I haven't experienced any issues yet.

Let me know if you need any more information! Thank you!

**Comment by QuestingPet** [comment]
In case it helps, this is the only hiccup I had with the mod disabled, and it was a server tick that took ~22s (much shorter than the 10 minutes from the mod): https://spark.lucko.me/oyZdspCMe8

Not sure how/why entity pathfinding took so long, as I just have a small mob farm with Blursed Earth where all mobs get fanned and crushed immediately.

**Comment by MaxNeedsSnacks** [comment]
The original spark logs posted in this issue are unfortunately no longer valid... Do you mind creating a new issue whenever this happens again? I might have a hunch regarding what this might be related to...
