### ISSUE TITLE
Chunkloading conflicts with Advanced Rocketry

### ISSUE THREAD

**Issue by NoaHimesaka1873** [MaxNeedsSnacks/roadrunner#53]
### Reproduction Steps
1. Build the rocket
2. ???
3. CRASH!

### Crash Report File
https://gist.github.com/NoaHimesaka1873/87d25e3aa9b8d22c3a933e4b5970a613

**Comment by embeddedt** [comment]
Advanced Rocketry versions for 1.16.5 are, for the most part, no longer publicly available, so I don't plan to fix this. However, if someone digs up a version of that mod and submits a PR fixing the bug, it will be accepted.
