### ISSUE TITLE
Requesting config to disable maths mixins for client side entity movement due to possible incompatibility

### ISSUE THREAD

**Issue by NighthowlerStudios** [MaxNeedsSnacks/roadrunner#54]
**Is your feature request related to a problem? Please describe.**
I am currently investigating modpack framerates and it seems some maths of roadrunner are taking a long time.  

**Describe the solution you'd like**
Can I please have provided the mixin disable for the classes of `common.entity.movement`?  if this is already doable can you please direct me to where and how to place this in the configs.

**Describe alternatives you've considered**
I am still finding other mods that are taking a long time on the render thread and finding solutions for them as well.

**Additional context**
The long frame time only occurs around 20 times per second, which means it's a client maths problem I am dealing with.  it is causing maximum framerate and 0.1% low framerate to drop in ways it usually shouldn't.

**Comment by NighthowlerStudios** [comment]
as seen on this profile the maximum time it takes for lithium's algorithm is 16 milliseconds over the course of this 30 second profile, which is unusually large compared to previous tests with certain mods removed that I did not keep track of.  Dungeons Mod also seems to have an issue.

https://spark.lucko.me/kBOWSS9zaR

**Comment by MaxNeedsSnacks** [comment]
`mixin.entity.collisions`, `mixin.entity.fast_suffocation_check` and `mixin.chunk.count_oversized_blocks` are the only mixins that refert to anything from that package to my knowledge, if you want to, you can try disabling those using the [rule overrides](https://github.com/MaxNeedsSnacks/roadrunner/wiki/Configuration-Files#rule-overrides) and see whether that increases your framerate ^^

**Comment by NighthowlerStudios** [comment]
sorry for the delay, had to deal with modlist corruption on curseforge that was affecting my export process.

as expected there was no real change in removing these mixins, in fact the tick time on the server side **doubled** from 5ms to 9ms.  thanks anyway.
