### ISSUE TITLE
Sophisticated Backpacks desyncing/forgetting/switching-between-players slots of their inventory

### ISSUE THREAD

**Issue by NighthowlerStudios** [MaxNeedsSnacks/roadrunner#57]
all information on the bug I'm tracking can be found here

https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/403

is there any mixin rules I can add that might be dealing with nbt/inventory packets that I can turn off for testing for conflict?

**Comment by MaxNeedsSnacks** [comment]
Is this issue still valid? I see it was closed on the SB end because you just ended up giving people backpacks with the same UUID by accident :p

**Comment by NighthowlerStudios** [comment]
as far as I can tell at least in regards to my specific circumstances, no, because I was able to verify via testing that having the tags set in starting gear was what broke it.

I advise however, that if you are still having similar trouble in other circumstances, that you add code that makes a fresh uuid if there is a duplicate found on the server, and make sure the contents get retained during deduplication properly.

**Comment by MaxNeedsSnacks** [comment]
Well, that would be on them to solve then, we don't interfere with any of SB's code ^^

**Comment by NighthowlerStudios** [comment]
yeah no problem.
