### ISSUE TITLE
Roadrunner and in control mods "seesky" rule break the game, no more terrain will load, freezes game on world save

### ISSUE THREAD

**Issue by JetpackRescue** [MaxNeedsSnacks/roadrunner#59]
Here's my bug report on in control mod, he said the issue is likely with roadrunner.
https://github.com/McJtyMods/InControl/issues/307

The "seesky" rule in in control mod is incompatible with the mod roadrunner. Seesky checks to see if the block can see the sky so you can spawn mobs that aren't underground or in buildings etc.

Example:
In spawn.json:

    "mob": "minecraft:iron_golem",
    "onjoin": "true",
    "seesky": true,
    "result": "allow"
  }```

If seesky is included anywhere in any rule, the game only loads a small portion of terrain, it will not load anything else, you can fly off into the sunset and the game will not load more terrain. When you click "save and quit to title" it will freeze on "saving world", clicking the game a million times wont even crash minecraft, you have to kill the process in task manager. If you click the windows close X, it just freezes, you now have to kill the process.

The only mods I have installed are roadrunner and incontrol. the only config i've adjusted is spawn.json, and the only thing I added is the code above. If I remove "seesky" from it, the game works normally.

**Comment by embeddedt** [comment]
Probably fixed by 1.5.0, please open a new issue report with up-to-date mods if not.
