### ISSUE TITLE
"Crash" on startup

### ISSUE THREAD

**Issue by Drakoflame** [MaxNeedsSnacks/roadrunner#6]
Not entirely to sure what is happening, it's not a crash per se as it doesn't generate a crash report, so I took the debug and log and threw them into pastebin's. I'm not 100% sure what is happening when glancing over the logs, just something about a mixin not being found:

Latest: https://pastebin.com/CeBEPAHC
Debug: https://pastebin.com/kTHCZM4j
(Note, the above to are _WITH_ Optifine/Optiforge installed. I'm well aware that these mods **WILL** cause issues, I still run with them just in case. Below are the Latest and Debug logs _without_ Optifine/forge installed. I figured I would include both so that you guys know 100% without-a-doubt that Optifine doesn't work, and you can add it to your incompatibilities list)

Latest: https://pastebin.com/GZC89dSF
Debug: https://pastebin.com/hGqWJQsM

**Comment by MaxNeedsSnacks** [comment]
I'm... a bit of an idiot and forgot to remove the mixins I deleted from the mixins.json lol

Combine that with architectury-loom deciding to break on me (and 0.10.0 not being ready to use yet) so I couldn't test the jar before I pushed and... well, this happened haha

**Comment by Drakoflame** [comment]
Glad I could help XD

**Comment by MaxNeedsSnacks** [comment]
Haha thanks for the reminder, it should be up as 1.2.1 on CurseForge (or GitHub releases if CF decides to take its time again) once https://github.com/MaxNeedsSnacks/roadrunner/runs/3784441646?check_suite_focus=true completes
