### ISSUE TITLE
Critical Injection Failure.

### ISSUE THREAD

**Issue by Romoslayer** [MaxNeedsSnacks/roadrunner#64]
Critical injection failure: Redirector redirectChunksListClone(Ljava/lang/Iterable;)Ljava/util/ArrayList; in roadrunner.mixins.json:alloc.chunk_ticking.ServerChunkManagerMixin failed injection check

I am not sure how to reproduce this crash.

Road Runner version: 1.16.5-1.4.1

Logs:
[latest.log](https://github.com/MaxNeedsSnacks/roadrunner/files/8491403/latest.log)

**Comment by MaxNeedsSnacks** [comment]
RoadRunner isn't compatible with Does It Tick?, as it overlaps with many of our mixins and additionally attempts to solve performance issues by just stopping things from ticking entirely, which will break many assumptions within RR
