### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by RexGuard** [MaxNeedsSnacks/roadrunner#67]
i added them to my mod pack and a red message appear

https://mclo.gs/QO12t66

my mods are
-MCMT
-Performant
-FastFurnace
-FastWorkbench
-FerriteCore
-AI Improvements
-StarLight
-Random  Patches

**Comment by RexGuard** [comment]
mods are only fps boosting
the others did not conflict with these mods

**Comment by MaxNeedsSnacks** [comment]
See #56, RoadRunner is not and will never be compatible with Performant
