### ISSUE TITLE
RoadRunner's random crash? (1.16.5)

### ISSUE THREAD

**Issue by PhweeDev** [MaxNeedsSnacks/roadrunner#68]
https://paste.gg/p/anonymous/146f5b360ea242bba0796565ef457154

I was just exploring randomly, swimming through a river and randomly crashed.

**Comment by PhweeDev** [comment]
Happened again and randomly. I was just mining in the nether when my game randomly froze and crashed.

**Comment by MaxNeedsSnacks** [comment]
This looks a lot like #12, I have no idea why it would ever try to add the same nearby entity listener twice; the only time I'd think that would happen is if the same **entity** was added twice...

**Comment by PhweeDev** [comment]
I know you just completed this, but I wanted to note it happens in servers too.

https://paste.gg/p/anonymous/e6a31fad74ed4d23bd6c9c3375aff987
