### ISSUE TITLE
RoadRunner is Incompatible with SimplyImprovedTerrains

### ISSUE THREAD

**Issue by 704-Prod** [MaxNeedsSnacks/roadrunner#69]
### Reproduction Steps
Install SimplyImprovedTerrain 1.16.5 & Roadrunner 1.16.5 mods into folder and run game
Game should crash

### Additional Information
I asked help of discord companions and they said that simply improved terrains is modifying terrain in the end which somehow conflicts with RoadRunner

Not sure if you're willing to work on a version like 1.16.5, but I figured I'd report the crash anyways

### Crash Report File
[GitHub Gist](https://gist.github.com/704-Prod/5b083bcc3de598880f01d6fc94eee299/)

**Comment by embeddedt** [comment]
Should be fixed in 1.5.0.
