### ISSUE TITLE
Several incompats with workarounds for Special AI mod

### ISSUE THREAD

**Issue by NighthowlerStudios** [MaxNeedsSnacks/roadrunner#70]
### Reproduction Steps
Randomly, but quite commonly, roadrunner will crash if a special ai special type of mob spawns in a structure (a large one is best to test, such as a stronghold) due to the way the chunk checker functions.  

I can confirm it is fixed if I disable such mixin ```mixin.world.mob_spawning```

### Crash Report File
[crash-2022-06-08_16.22.41-server.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/8992180/crash-2022-06-08_16.22.41-server.txt)

### Additional Information
Performed fix on Kaleidio's Battle Pack 4.3.6.  crash occurs with these two mods alone

**Comment by NighthowlerStudios** [comment]
Similarly, if an entity is tracking the player's position, there can be a crash if the entity is killed first which can be fixed via ```mixin.ai.goal```

[crash-2022-06-29_15.43.07-server.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/9012117/crash-2022-06-29_15.43.07-server.txt)

**Comment by NighthowlerStudios** [comment]
Similarly, if an entity is trying to make a point of interest for a village, it will have a chance to crash fast retrieval.SerializingRegionBasedStorage
[message (1).txt](https://github.com/MaxNeedsSnacks/roadrunner/files/9048850/message.1.txt)

**Comment by P3rf3ctXZer0** [comment]
Are you also trying to run a pixelmon server with roadrunner XD all these fixes apply ... thanks for posting thing @Kaleidio

**Comment by embeddedt** [comment]
This issue report is quite old, contains multiple issues, and there are a lot of mods installed. If any of these problems remain in 1.5.0 or newer, please open a new issue report with minimal mods and instructions on how to reproduce.

**Comment by NighthowlerStudios** [comment]
> This issue report is quite old, contains multiple issues, and there are a lot of mods installed. If any of these problems remain in 1.5.0 or newer, please open a new issue report with minimal mods and instructions on how to reproduce.

I stated in the original issue that:

> Performed fix on Kaleidio's Battle Pack 4.3.6. **crash occurs with these two mods alone**

Which means the crash occurred with Special AI and Roadrunner alone for me.

What I followed up with was a list of every rule I had to disable in order to fix compatibility.

Your response here seems confused by the other person who reported about Pixelmon, which was not at all related to the original issue I posted about.

I included the name Kaleidio's Battle Pack purely for reference on how I found it, and where I submitted a rules.properties file to curseforge that "fixes" the issue, so that you could see it too.  Remember, **I get the crash with only Special AI and Roadrunner installed, nothing else**
