### ISSUE TITLE
[1.16.5 save lock] fast_retrieval can lock a multiplayer server when retrieving unfinished village chunks

### ISSUE THREAD

**Issue by NighthowlerStudios** [MaxNeedsSnacks/roadrunner#71]
Similarly, if an entity is trying to make a point of interest for a village, it will have a chance to crash fast retrieval.SerializingRegionBasedStorage
[message (1).txt](https://github.com/MaxNeedsSnacks/roadrunner/files/9048850/message.1.txt)

_Originally posted by @Kaleidio in https://github.com/MaxNeedsSnacks/roadrunner/issues/70#issuecomment-1175399940_

this issue is deemed separate as Special AI mixins were not involved whatsoever, however other mods such as Chocolate fix were.  see message.txt for crashlog.  latest.log does not apply as it does not give any information relevant.

the server cannot let the player at that position reenter

**Comment by embeddedt** [comment]
Option is disabled by default in 1.5.0
