### ISSUE TITLE
Crashed Minecraft on reload. 

### ISSUE THREAD

**Issue by Seteta** [MaxNeedsSnacks/roadrunner#72]
I'm not sure if Roadrunner is the cause, but it's the first thing that came to mind.
Here's the crash log
[crash-2022-07-13_01.47.49-client.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/9097613/crash-2022-07-13_01.47.49-client.txt)

**Comment by embeddedt** [comment]
This is a rendering crash, so it's unrelated to RoadRunner.
