### ISSUE TITLE
[1.16.5] JVM EXCEPTION_ACCESS_VIOLATION on Java 8 u51 using portal to leave overworld of non vanilla world type

### ISSUE THREAD

**Issue by NighthowlerStudios** [MaxNeedsSnacks/roadrunner#74]
mod collision with overworld two mod

all information is included already in here
https://github.com/SuperCoder7979/overworld-two/issues/25

**Comment by NighthowlerStudios** [comment]
fixed by disabling `mixin.gen`

**Comment by MaxNeedsSnacks** [comment]
This may sound a bit random, but I remember other also randomly crashing with JVM errors on older Java 8 updates (malte has told me that Immersive Engineering for instance used to as well), do you mind trying out a newer version like 8u341, and if that doesn't help could you provide the full log file for a bit more detail?

**Comment by NighthowlerStudios** [comment]
as stated in the mentioned issue, using newer JVMs does indeed fix the crash without any log complaints.

**Comment by embeddedt** [comment]
Java 8u51 is extremely ancient and has many bugs, not just this one. Please use a more modern version of Java (at least the latest version of Java 8, if not Java 11).

**Comment by NighthowlerStudios** [comment]
Java 8u51 is default for 1.16.5.  It's really difficult to convince modpack players to upgrade their JVM :/
