### ISSUE TITLE
Future Pack Interface problem

### ISSUE THREAD

**Issue by dimonchik121** [MaxNeedsSnacks/roadrunner#75]
![2022-09-10_21-23-14](https://user-images.githubusercontent.com/113259381/189496724-bcf4270c-c8ae-4593-afec-e11d2f7207c5.png)
The problem is that the game can't find the way to the pictures that indicate crafting items from the mod

**Comment by dimonchik121** [comment]
Mod Future Pack 1.16.5

**Comment by embeddedt** [comment]
Likely a duplicate of https://github.com/MaxNeedsSnacks/roadrunner/issues/35.
