### ISSUE TITLE
server crashing when entering the nether

### ISSUE THREAD

**Issue by HyperFoxOne** [MaxNeedsSnacks/roadrunner#77]
i have a minecraft modded server and when i enter the nether with the roadrunner mod installed it crashes the server.
If I remove the roadrunner mod it does not crash so I believe that it is the cause.

### Crash Report File
https://pastebin.com/BeMg600r

The attachment is the latest log given that sometimes it could help, (as far as I know)

[latest.log](https://github.com/MaxNeedsSnacks/roadrunner/files/10253825/latest.log)

**Comment by Kasualix** [comment]
Disable elite mobs in dungeons libraries config may work.

**Comment by embeddedt** [comment]
Probably fixed by 1.5.0
