### ISSUE TITLE
1.17, 18, and 19 exist. Please update.

### ISSUE THREAD

**Issue by MagmaSlime123** [MaxNeedsSnacks/roadrunner#78]
**Is your feature request related to a problem? Please describe.**
Yes, this mod is on an outdated MC version.

**Describe the solution you'd like**
Please update. Newer versions are out.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A.

**Comment by ma-gician** [comment]
use canary! it is only available for 1.17, 18, and 19 😄  https://www.curseforge.com/minecraft/mc-mods/canary

**Comment by MaxNeedsSnacks** [comment]
We don't really have an interest in perpetrating the 4300 different Lithium fork situation on versions between 1.16, so yeah, some other fork is likely to produce *similar* results at least. As for 1.18, we did start development on that at some point, but besides one FTB modpack not much came of it
