### ISSUE TITLE
Crash when loading chunk with Roadrunner installed

### ISSUE THREAD

**Issue by iWalk809** [MaxNeedsSnacks/roadrunner#79]
I was traveling through an Ocean in the overworld, and then found an dungeon. after swimming a few blocks away, the server froze and then crashed.
### Crash Report File
https://gist.github.com/iWalk809/26daebf8aa45e55f77bb1b0ef7886a1c

**Comment by embeddedt** [comment]
This is caused by lighting engine being manipulated on the wrong thread, I don't think RoadRunner caused this crash. It could be an issue with Special Mobs, or with Mohist.
