### ISSUE TITLE
Incompatibility with the starlight mod.

### ISSUE THREAD

**Issue by StormDragon-64** [MaxNeedsSnacks/roadrunner#8]
I tried using this mod with another performance mod, called starlight, which changes the lighting engine. There are no crashes or anything when starting the game, but when I try to load into a world, it gets stuck at 0%, and 1.16's chunk loading progress box stays black. I was using starlight's latest forge 1.16 version, 1.0.0-RC2.

**Comment by Sshmoob** [comment]
I also have optifine, if that makes a difference.

**Comment by MaxNeedsSnacks** [comment]
I'm... pretty sure OptiFine and Starlight aren't even compatible, but yes, having OF installed does make a difference. Can you try reproducing it without OF and posting your latest / debug log files here please?

**Comment by Sshmoob** [comment]
No, I was using Starlight and optifine before, and it worked fine, but then I tried using this mod with it, and like I said before, when I try to load a world it gets stuck at 0%.

**Comment by Sshmoob** [comment]
When I deleted optifine, the same thing happened, but eventually the game just crashes. It might be crashing because I have a bad pc, though.

**Comment by Sshmoob** [comment]
**_Crash_** log: 

https://pastebin.com/G4P3ap8y

**Comment by Sshmoob** [comment]
**Normal** Log:

https://pastebin.com/KbdJPMDA

**Comment by MaxNeedsSnacks** [comment]
That's... unrelated to Starlight or Optifine and basically just ties into #7. I'll have a hotfix out once GitHub Actions starts working again
