### ISSUE TITLE
bound must be positive exception with roadrunner 1.4.1

### ISSUE THREAD

**Issue by mattrix444** [MaxNeedsSnacks/roadrunner#80]
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

1. load game, create a world and then die
2. try to create a new world afterwards
3. sit back and enjoy the crash to desktop

i think roadrunner is involved since its mentioned in the crash log i have provided, skyblock builder is also mentioned and have informed the dev. i believe one of the mods is trying to pass a non positive integer to a function and the game doesnt like it.

### Crash Report File
https://gist.github.com/mattrix444/af413700d8e7a8aa5714b3251cc0314d

### Additional Information
have a great day

**Comment by embeddedt** [comment]
This looks a lot more likely to be an issue with Skyblock Builder than RoadRunner, we don't change anything about the random generator for structures.

**Comment by mattrix444** [comment]
heroic replying times well done.
