### ISSUE TITLE
game crashed

### ISSUE THREAD

**Issue by Natedogwoooof** [MaxNeedsSnacks/roadrunner#81]
### Reproduction Steps
my save is too big to upload, but I was in village mania dimension from chaos awakens female villager. It tryed to add a listener for the 2ed time, so was just in village mania fighting robots then my game crashed
1i don't know why it happened

### Crash Report File
https://gist.github.com/Natedogwoooof/b1be4d0da8f373c3c7f64ed15735f26e

### Additional Information
i have lots of mods installed, main culprits 
roadrunner
morph
minecraft comes alive reborn
chaos awakens

**Comment by embeddedt** [comment]
Probably fixed by 1.5.0
