### ISSUE TITLE
Conflict between Canary and Roadrunner mods

### ISSUE THREAD

**Issue by FEXYPEPSY** [MaxNeedsSnacks/roadrunner#82]
I've been using Aternos server hosting, and upon reviewing the crash log, I discovered a conflict between the Canary mod and Roadrunner. Removing the Roadrunner mod resolves the issue, allowing the server to start without any problems.

Here's the log file from mclo.gs via the link. At the bottom, starting at line 1463, is the section regarding the conflict between Canary and Roadrunner.

https://mclo.gs/NKNDm3R

**Comment by MaxNeedsSnacks** [comment]
This is to be expected, both are forks of Lithium. Remove one of the two mods and it should launch
