### ISSUE TITLE
Crash on startup with Extreme Reactors, Immersive Engineering, APTweaks

### ISSUE THREAD

**Issue by Cynix32** [MaxNeedsSnacks/roadrunner#9]
### Reproduction Steps

1. Install ZeroCore (dependency/lib), Extreme Reactors, APTweaks, Immersive Engineering, and Roadrunner
2. Start minecraft forge on vanilla launcher
3. crash 

removing roadrunner solves the problem.

### Crash Report File
https://pastebin.com/HbwGeFYk

### Additional Information
Forge 36.2.8
MC 1.16.5
Java 8

Mod jars, with their versioned filename as downloaded from curseforge:
ImmersiveEngineering-1.16.5-5.0.3-138.jar
ExtremeReactors2-1.16.5-2.0.29.jar
ZeroCore2-1.16.5-2.1.4.jar
adaptive_performance_tweaks_1.16.5-1.1.4.jar
RoadRunner-mc1.16.5-1.2.1.jar

**Comment by NBZion** [comment]
have you tried using other launchers E.G. GDLauncher or MultiMC?

**Comment by malte0811** [comment]
This is unrelated to the launcher, see #7 (the exact crash is different, but the cause is the same).
